//! \file make_help.c
//! Converts help.txt into help.c.
//==============================================================================
// AEPHEM - an astronomical ephemeris and reduction library.
// Copyright 2012 Adam Hincks, Canadian Institute for Theoretical Astrophysics.
//
// This file is part of AEPHEM.
//
// AEPHEM is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// AEPHEM is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with AEPHEM.  If not, see <http://www.gnu.org/licenses/>.
//==============================================================================

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define INPUT "help.txt"
#define OUTPUT "help.c"

enum stage_t {
  METHOD = 0,
  SHORT_DESC,
  LONG_DESC,
  PARAM,
  RETURN,
  SEE
};

int main(int argc, char *argv[]) {
  char line[128], method_name[128];
  int i, stage, stage_start, switch_type, skip_char;
  FILE *fp_in, *fp_out;

  if ((fp_in = fopen(INPUT, "r")) == NULL) {
    fprintf(stderr, "Could not open %s for reading.\n", INPUT);
    exit(0);
  }
  if ((fp_out = fopen(OUTPUT, "w")) == NULL) {
    fprintf(stderr, "Could not open %s for reading.\n", OUTPUT);
    exit(0);
  }

  fprintf(fp_out, "//! \\file help.c\n"
    "//! Python docstrings.\n"
    "//! This file was generated by make_help on " __DATE__ " at " __TIME__
      ".\n"
    "//========================================================================"
      "======\n"
    "// AEPHEM - an astronomical ephemeris and reduction library.\n"
    "// Copyright 2012 Adam Hincks, Canadian Institute for Theoretical "
      "Astrophysics.\n"
    "//\n"
    "// This file is part of AEPHEM.\n"
    "//\n"
    "// AEPHEM is free software: you can redistribute it and/or modify\n"
    "// it under the terms of the GNU General Public License as published by\n"
    "// the Free Software Foundation, either version 3 of the License, or\n"
    "// (at your option) any later version.\n"
    "//\n"
    "// AEPHEM is distributed in the hope that it will be useful,\n"
    "// but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
    "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
    "// GNU General Public License for more details.\n"
    "//\n"
    "// You should have received a copy of the GNU General Public License\n"
    "// along with AEPHEM.  If not, see <http://www.gnu.org/licenses/>.\n"
    "//========================================================================"
    "======\n\n");

  stage = METHOD;
  while (fgets(line, 127, fp_in) != NULL) {
    // Strip newline.
    while (line[strlen(line) - 1] == '\n' ||
           line[strlen(line) - 1] == '\r')
      line[strlen(line) - 1] = '\0';

    // Initialisation.
    skip_char = 0;

    // Warn on long lines.
    if (strlen(line) > 72) {
      printf("Warning: the following line is longer than 72 characters:\n");
      printf("  %s\n", line);
    }

    // Check for switch to parameter or return.
    if (line[0] == '\\') {
      switch (tolower(line[1])) {
        case 'p':
          switch_type = PARAM;
          break;
        case 'r':
          switch_type = RETURN;
          break;
        case 's':
          switch_type = SEE;
          break;
        default:
          fprintf(stderr, "Unknown switch in the following line:\n",
                          "  %s\n", line);
          exit(0);
      }

      switch (stage) {
        case PARAM: case LONG_DESC:
          stage = switch_type;
          stage_start = 1;
          break;

        case METHOD:
          fprintf(stderr, "Was expecting new method on the following line:\n",
                          "  %s\n", line);
          exit(0);

        case SHORT_DESC:
          fprintf(stderr, "Was expecting short description on the following "
                          "line:\n  %s\n", line);
          exit(0);

        case RETURN:
          switch (switch_type) {
            case PARAM:
              fprintf(stderr, "No more parameters allowed after \\r switch!\n"
                            "  %s\n", line);
              exit(0);
            case RETURN:
              fprintf(stderr, "Only one \\r switch allowed per method!\n"
                            "  %s\n", line);
              exit(0);
            case SEE:
              stage = SEE;
          }
          break;

        case SEE:
          fprintf(stderr, "No switches allowed after \\s switch!\n"
                          "  %s\n", line);
          exit(0);
      }
    }

    if (stage_start) {
      // Get rid of the switch.
      if (stage == PARAM || stage == RETURN || stage == SEE)
        for (skip_char = 2; line[skip_char] == ' '; skip_char++);
      }
    }

    // Parse the line.
    switch (stage) {
      case METHOD:
        if (!strlen(line))
          continue;

        for (i = 0; i < 128 && line[i] != '('; i++);
        strncpy(method_name, line, i - 1);
        method_name[i] = '\0';
        fprintf(fp_out, "#define DOCSTRING_%s \\\n", method_name);
        fprintf(fp_out, "  \"%s\\n\" \\\n", line);

        stage = SHORT_DESC;
        break;

      case SHORT_DESC:
        if (!strlen(line)) {
          printf("Was expecting short description for method %s!\n",
                 method_name);
          exit(0);
        }

        fprintf(fp_out, "  \"%s\\n\" \\\n", line);

        stage = LONG_DESC;
        stage_start = 1;
        break;

      case LONG_DESC:
        if (!strlen(line) || stage_start) {
          fprintf(fp_out, "  \"\\n\" \\\n");
          stage_start = 0;
        }
        else
          fprintf(fp_out, "  \"%s\\n\" \\\n");

        break;
    }
  }
}
